spring:
  application:
    name: calendar
  datasource:
    url: jdbc:postgresql://localhost:5432/calendar
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    #Even if a method is annotated with @Transactional, it will not acquire a connection at the start of the method but
    #only when it needs to hit the database.
    hikari:
      auto-commit: false
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: postgres
    password: postgres
    baseline-description: "init"
    baseline-version: 0
    locations: classpath:db/migration
  mail:
    host: smtp.gmail.com
    port: 587
    username: springbootsandbox@gmail.com
    password: jyfcxcmhcxetdxkz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: localhost
      port: 6379
  jackson:
    mapper:
      accept-case-insensitive-enums: true
  docker:
    compose:
      lifecycle-management: start_only
      file: classpath:/docker-compose.yaml
rsa:
  private_key: classpath:certs/private.pem
  public_key: classpath:certs/public.pem

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: TRACE
        transaction: TRACE