spring:
  application:
    name: google_calendar_clone
  datasource:
    url: jdbc:postgresql://localhost:5432/google_calendar_clone
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    #Even if a method is annotated with @Transactional, it will not acquire a connection at the start of the method but
    #only when it needs to hit the database.
    hikari:
      auto-commit: false
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: postgres
    password: postgres
    baseline-description: "init"
    baseline-version: 0
    locations: classpath:db/migration
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  docker:
    compose:
      lifecycle-management: start_only
rsa:
  private_key: classpath:certs/private.pem
  public_key: classpath:certs/public.pem

logging:
  level:
    org:
      springframework:
        security: TRACE
        web: DEBUG
        transaction: TRACE
        orm:
          jpa:
            JpaTransactionManager: TRACE